---
title: "Profile"
output:
  html_document:
    toc: true
---
## Education  
**PhD in Cognition and Cognitive Neuroscience**  
University of Massachusetts Amherst, United States  
Sept. 2022 - present  

**MA in Linguistics**  
National Tsing Hua University, Hsinchu, Taiwan  
Thesis: *Neural responses to syllable gaps in Taiwanese Mandarin: an event-related potential study*  
Sept. 2016 - Feb. 2020  

**BSc in Interdisciplinary Program of Life Sciences**  
with specialties in *Life Science* & *Foreign Languages and Literature*  
National Tsing Hua University, Hsinchu, Taiwan  
Sept. 2012 - Jul. 2016  

<div style="margin-bottom:35px;">
</div>

## Teaching 
**Instructor of Record *for* First-Year Seminar**  
**(Unlocking Knowledge: The Open Science Movement)**  
College of Natural Sciences  
University of Massachusetts Amherst, United States  

**Instructor of Record *for* Cognitive Psychology**  
**Teaching Assistant *for* Cognitive Psychology**  
**Teaching Assistant *for* Methods of Inquiry in Psychology**  
**Teaching Assistant *for* Introductory Psychology**  
Department of Psychological and Brain Sciences  
University of Massachusetts Amherst, United States  

**Teaching Assistant *for* Experimental phonetics**  
**Teaching Assistant *for* Phonology (I)**  
**Teaching Assistant *for* Undergraduate Phonetics**  
Intitute of Linguistics  
National Tsing Hua University, Hsinchu, Taiwan  

<div style="margin-bottom:35px;">
</div>

## Additional Training 
**2023 Summer Institute Student**  
Linguistic Society of America  
University of Massachusetts Amherst, United States

**Neuroscience and Neuroimaging Specialization**  
Johns Hopkins University  
(via [Coursera](https://coursera.org/share/d619ef92db4ef6d85e40896bdc5ed8ec))

**Visiting Student**  
2016 International Summer College  
Ewha Womans University, Seoul, Korea  
  
**2014 Summer School Student**  
Institute of Statistical Science  
Academia Sinica, Taipei, Taiwan  

<div style="margin-bottom:35px;">
</div>

## Selected Awards & Honors
**Excellent Student Paper Award**  
Taiwan Society of Cognitive Neuroscience Annual Meeting, 2025  

**Graduate School Predissertation Research Grant (US$1,300)**  
University of Massachusetts Amherst, 2024

**Graduate Study Award (US$71,652)**  
Foundation for Scholarly Exchange (Fulbright Taiwan), 2022 - 2024

**University Graduate Fellowship (US$24,821)**  
University of Massachusetts Amherst, 2022 - 2023    

**Honorary Member of Phi Tau Phi Scholastic Honor Society**  
Nominated by National Tsing Hua University, 2016  

**New Undergraduate Merit Scholarship (NT$400,000)**    
National Tsing Hua University, 2012 - 2016   

<div style="margin-bottom:35px;">
</div>

## Working

**Research Assistant**  
National Tsing Hua University, Hsinchu, Taiwan  
(see details [here](past.html))

**Webmaster**  
Institute of Linguistics  
National Tsing Hua University, Hsinchu, Taiwan  

**Research Assistant of Book Purchase Project**  
Project: Conservation and revitalization of endangered languages  
PI: [Prof. Hsiu-chuan Liao](http://ling.hss.nthu.edu.tw/faculty/hcliao/index.html)  

**Summer Intern in 2013**  
Dr. Cecilia Koo Botanic Conservation Center, Pingtung, Taiwan  
Project: A comparative study of leaf morphology of native *Camellia* species in Taiwan  
Onsite Supervisor: Mr. Jun-Nan Yang