---
title: "Miscellaneous"
---
<div style="margin-bottom:35px;">
</div>

I assisted in the following projects with varying duties:  

#### Cognition, Humor and Affect Neuroscience Lab
PI: Prof. Yu-Chen Chan

- Sex differences in humor styles and coping humor
    - collected behavioral, fMRI, and EEG data
    - general laboratory management
    - mentored undergraduate students
    
#### Neurolinguistics Laboratory
PI: Prof. Jo-Fu Lotus Lin

- Pre-attentive processing of tone sandhi in Mandarin Chinese
    - analyzed EEG data (preprocessing and statistical tests)
    - collected and arranged EEG data according to the BIDS format
    - wrote Praat scripts to edit a batch of auditory stimuli
    - created E-prime programs for controlling experiments
    
#### Phonetics Laboratory  
PIs: Prof. Yueh-chin Chang & Prof. Feng-fan Hsieh  

- Gemination in prosodically weak elements in Taiwanese Southern Min and Hakka  
    - recorded, transcribed, and analyzed acoustic data  
    
- A phonetic and phonological study of Penang Hokkien  
    - arranged and analyzed acoustic data  
    - recruited and mentored a team of 4 members  
    
- Coarticulatory patterns of nasal rimes in Taiwanese Mandarin and Southern Min  
    - ran electromagnetic articulography experiments  
    - ordered and managed laboratory supplies  
    - wrote customized R and MATLAB scripts  

#### Language and Cognitive Neurology Laboratory  
PI: Prof. Fan-Pei Gloria Yang  

- Different cognitive mechanisms underlying Chinese and Chinese Sign Language  
  (Co-PI: Prof. Minghu Jiang from Tsinghua University, Beijing, China)  
    - assisted in experimental design and writing the grant proposal  
    - applied for the approval of the research ethics committee  
    
- Investigation of enhanced cognitive networks with task-activated fMRI and DTI  
    - scheduled and guided the cognitive training sessions  
    - developed the training materials in Mandarin Chinese  

## Selected coursework projects  
I have written term papers based on these projects. If you are interested in these works, the manuscripts and slides are available upon request.

- The effect of perceptual similarity on second language learners’ processing of Taiwanese tone sandhi  
*L2 Phonological Acquisition: Theory, Methods, and Pedagogy*  
Instructor: Prof. Tsung-Ying Chen  

- The exception of NC̥ effect in Standard Malay  
(with Phaik Gek Lim)  
*Phonology (II)*    
Instructor: Prof. Feng-fan Hsieh  

- An acoustic and electroglottographic study on contextual variations of Korean stop contrast  
(with Phaik Gek Lim and Dabin Eun)  
*Articulatory Phonetics*  
Instructor: Prof. Yueh-chin Chang  
