
<div style="margin-bottom:35px;">
</div>

## Conference presentations  
**Chang, C.-Y.** & L. D. Sanders (2025). Decoding phonetic cue weighting from electroencephalography responses to naturalistic speech. Poster to be presented at the Society for the Neurobiology of Language 17th Annual Meeting, September 12-14, Washington DC, United States.  

**Chang, C.-Y.** & L. D. Sanders (2025). The relationship between musical experience and cue reweighting in speech perception. Poster to be presented at the 2025 Annual Meeting of the Cognitive Science Society, July 30-August 2, San Francisco, United States.  

**Chang, C. Y.**, A. Jesse, L. D. Sanders (2025). Do listeners access abstract morphological representations while processing speech? A representational similarity analysis of event-related potentials. Poster presented at 32th Annual Meeting of the Cognitive Neuroscience Society, March 29-April 1, Boston, United States.  

**Chang, C.-Y.** & L. D. Sanders (2025). Decoding phonetic cue weighting from EEG: a representational similarity approach. Poster presented at the 2025 Annual Meeting of Taiwan Society of Cognitive Neuroscience, January 11, Taoyuan, Taiwan.  

**Chang, C.-Y.** & L. D. Sanders (2024). On the temporal aspect of post-consonantal fundamental frequency perturbation in English voicing perception. Talk given at the 187th Meeting of the Acoustical Society of America, November 18-22, Virtual meeting.  

**Chang, C.-Y.** & L. D. Sanders (2024). Testing the roles of post-consonantal F0 perturbation and noise in tonogenesis. Talk given at the 60th Annual Meeting of the Chicago Linguistic Society, April 26-28, Chicago, United States.  

**Chang, C.-Y.**, A. Jesse, L. D. Sanders (2023). Event-related potential responses to morphophonological violations. Talk given at Hanyang International Symposium on Phonetics and Cognitive Sciences of Language 2023, May 26-27, Seoul, South Korea.  

**Chang, C.-Y.** & F.-F. Hsieh (2020). Tone-consonant co-occurrence probability in Mandarin. Talk given at the 11th International Conference of Experimental Linguistics, October 12-14, Virtual meeting. [[Youtube video]](https://youtu.be/b4HUAjVrkzw)   

**Chang, C.-Y.** (2020). An acoustic study of monophthongs in Takibakha Bunun. Paper presented at National Conference on Linguistics 2020, November 14, Kaohsiung, Taiwan.  

**Chang, C.-Y.** & F.-F. Hsieh (2019). Neural responses to tonal and segmental gaps in Mandarin Chinese. Talk given at Hanyang International Symposium on Phonetics and Cognitive Sciences of Language 2019, May 24-25, Seoul, South Korea.  

Yang, F.-P. G., **C.-Y. Chang**, S. C. LaHue, S. R. Cooper, T. L. Luks, P. Mukherjee (2016). The semantic memory deficits after traumatic brain injury: a functional magnetic resonance imaging study. Poster presented at the 22nd Annual Meeting of the Organization for Human
Brain Mapping, June 26-30, Geneva, Switzerland.  

<div style="margin-bottom:35px;">
</div>

## Invited presentations
**Chang, C.-Y.** (2023). Probing the mental representation of speech sounds with nonexistent combinations. Talk given at Taiwanese Young Researcher Association, April 29, Virtual meeting. [[Youtube video]](https://youtu.be/W2O3UshuI4M?si=LgfeFfVBdJzGM1Tu)  

**Chang, C.-Y.**, F.-F. Hsieh, Y.-C. Chang, J.-F. L. Lin (2021). Tracking lexical tone processing in the human auditory pathway. Poster presented at Symposium of NTHU Multidisciplinary and Competitive Programs for MOE Higher Education Sprout Project, December 8, Virtual meeting.   

**Chang, C.-Y.** & F.-F. Hsieh (2020). Electrophysiological responses to tone- and segment-induced phonotactic anomalies. Paper presented at Exploring Interfaces #4: Natural Language and Neural Network, November 27, Hsinchu, Taiwan.  