---
title: "Ongoing projects"
---
<div style="margin-bottom:35px;">
</div>

**Testing the roles of post-consonantal F0 perturbation and noise in tonogenesis**  
(Advised by Dr. Lisa Sanders)  

F0 perturbation caused by adjacent consonants is thought to be a possible trigger of tonogenesis, i.e., the emergence of tone in initially non-tonal languages. During this process, the F0 difference presumably becomes larger in magnitude and longer in duration, making it perceptually more salient. Thus, listeners may possibly increase the perceptual weight of F0 while decreasing the weight of consonant phonation.  

Using English stop voicing as a testing case, this study examines cue weightings of VOT and F0. Specifically, we ask: 

- Does **the temporal extent of F0 perturbation** contribute to voicing perception?
- As F0 is more robust to noise, does **the presence of noise** modulate the F0 perturbation effects?

<div style="margin-bottom:35px;">
</div>

**How learnable is adult statistical learning? A critical review of literature since Saffran, Newport, and Aslin (1996)**  

[Saffran, Newport, and Aslin (1996)](https://doi.org/10.1006/jmla.1996.0032) demonstrated that adults can recognize words of an artificial language above chance after mere exposure to statistical regularities in the speech stream. This seminal work led to a resurgence of language scientists’ interests in how experience contributes to language acquisition. Although statistical learning in adults has been replicated in many studies, null effects have also been reported in the literature. Therefore, this project aims to:  

- critically review the statistical analyses performed by Saffran, Newport, and Aslin (1996)  
- conduct a publication-bias-adjusted meta-analysis of subsequent literature to estimate effect size  

<div style="margin-bottom:35px;">
</div>

**ERP responses to violations of morphophonological rules, phonological expectations, and phonetic cues**  
(PI: Dr. Lisa Sanders; Co-PI: Dr. Alexandra Jesse)

The phonetic realization of the English regular plural suffix is determined by its preceding context. When the stem ends with a non-sibilant sound, the suffix and the preceding sound agrees in voicing. It surfaces as /z/ after voiced sounds (e.g., [dogz] 'dogs') and /s/ after voiceless sounds (e.g., [kæts] 'cats').  

By presenting listeners with various types of violations of this morphophonological rule, this study aims to determine:  

1. the representation and processing of allomorphs during speech comprehension
2. whether congruency of phonetic cues and phonotactic status influence morphophonological processing
3. how predictability modulates other factors  